before_install:
  - sudo apt-get update
  - sudo apt-get -y install pandoc
  - sudo apt-get install texlive-latex-base
  - sudo apt-get install texlive-fonts-recommended
  - sudo apt-get install texlive-fonts-extra
  - sudo apt-get install texlive-latex-extra

script:
  - make all
  - git subtree push --prefix dist origin gh-pages
